
server:
  port: 8181  servlet:    context-path: /api
#  ssl:
#    key-store: keystore.p12
#    key-store-password: harshit
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#  

spring:  application:    name: myJobHunter
    
      datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sinha
    password: sinha12345
    
  jpa:    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:      ddl-auto: create
    #    driver-class-name: com.jdbc:postgresql.jdbc.Driver